name: Tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'
    
    - name: Cache Node dependencies
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install Node dependencies
      run: npm install --no-audit --no-fund
      working-directory: test
    
    - name: Run tests
      run: npm test
      continue-on-error: true
      timeout-minutes: 1

    - name: Update dashboard
      continue-on-error: true
      run: |
        jq -c --arg repo "$GITHUB_REPOSITORY" --arg commit "$GITHUB_SHA" \
          '{repo: $repo, commit: $commit, report: .}' report.json > event.json
        EVENT_SIG=`openssl dgst -sha256 -hmac ${{ secrets.DASH_TOKEN }} event.json | awk '{print $2}'`
        curl -m 5 -X POST \
          -H 'Content-Type: application/json' \
          -H "X-Hub-Signature-256: sha256=$EVENT_SIG" \
          --data-binary @event.json ${{ secrets.DASH_URL }}

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: Report
        path: report.html
        retention-days: 7
